version: '3.7'



services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
      #/usr/share/grafana/conf/provisioning
