version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
  tomcat:
    image: tomcat:11
    ports:
      - 8080:8080
    volumes:
      - ./metrics:/tmp/metrics
      - ./static.xml:/usr/local/tomcat/conf/Catalina/localhost/static.xml

