global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "test_metrics"
    scrape_interval: 30s
    scrape_timeout: 5s
    fallback_scrape_protocol: PrometheusText1.0.0
    scheme: http
    metrics_path: "/static/metrics"
    static_configs:
    - targets: ["tomcat:8080"]
      labels:
        testLabelKey: 'testLabelValue'

  - job_name: "backbox_exporter_metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
    - targets: ["blackboxexporter:9115"]
      labels:
        testLabel1: 'testValue1'

  - job_name: "blackbox_simple_india_production"
    scheme: http
    metrics_path: "/probe"
    params:
      target: ["https://api.simple.org/api/v3/ping"]
    fallback_scrape_protocol: PrometheusText1.0.0
    static_configs:
    - targets: ["blackboxexporter:9115"]
      labels:
        urlTarget: 'india-production'

  - job_name: "blackbox_simple_bd_production"
    scheme: http
    metrics_path: "/probe"
    params:
      target: ["https://api.bd.simple.org/api/v3/ping"]
    fallback_scrape_protocol: PrometheusText1.0.0
    static_configs:
    - targets: ["blackboxexporter:9115"]
      labels:
        urlTarget: 'bangladesh-prodution'



