global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "test_metrics"
    scrape_interval: 145s
    scrape_timeout: 5s
    fallback_scrape_protocol: PrometheusText1.0.0
    scheme: http
    metrics_path: "/static/metrics"
    static_configs:
    - targets: ["tomcat:8080"]
      labels:
        testLabelKey: 'testLabelValue'

  - job_name: "backbox_exporter_metrics"
    scheme: http
    metrics_path: "/metrics"
    static_configs:
    - targets: ["blackboxexporter:9115"]
      labels:
        testLabel1: 'testValue1'

  - job_name: "blackbox_simple_india_production"
    scheme: http
    metrics_path: "/probe"
    params:
      target: ["https://api.simple.org/api/v3/ping"]
    fallback_scrape_protocol: PrometheusText1.0.0
    static_configs:
    - targets: ["blackboxexporter:9115"]
      labels:
        country: 'ind'
        environment: 'prod'

  - job_name: "blackbox_simple_bd_production"
    scheme: http
    metrics_path: "/probe"
    params:
      target: ["https://api.bd.simple.org/api/v3/ping"]
    fallback_scrape_protocol: PrometheusText1.0.0
    static_configs:
    - targets: ["blackboxexporter:9115"]
      labels:
        country: 'bgd'
        environment: 'prod'

  - job_name: 'blackbox_exporter_probes'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets: [ 'https://api.simple.org/api/v3/ping' ]
        labels:
          country: 'ind'
          environment: 'prod'
      - targets: [ 'https://api.bd.simple.org/api/v3/ping' ]
        labels:
          country: 'bgd'
          environment: 'prod' 
      - targets: [ 'https://api-simple.health.gov.lk/api/v3/ping' ]
        labels:
          country: 'lka'
          environment: 'prod'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxexporter:9115  # The blackbox exporter's real hostname:port.


  - job_name: 'federate_central_prometheus'
    scheme: https
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
        'match[]':
          - '{__name__=~".+"}'
    static_configs:
      - targets: [ 'prometheus.simple.org' ]
        labels:
          country: 'test'
          environment: 'test'
    basic_auth:
      username: 'admin@simple.org'
      password: 'check_in_one_password'


