global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "test_metrics"
    scrape_interval: 30s
    scrape_timeout: 5s
    scheme: https
    metrics_path: "/simpledotorg/rtsl_pocs/master/prometheus_poc/metrics"
    static_configs:
    - targets: ["raw.githubusercontent.com"]
    
