global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "test_metrics"
    scrape_interval: 30s
    scrape_timeout: 5s
    fallback_scrape_protocol: PrometheusText1.0.0
    scheme: http
    metrics_path: "/static/metrics"
    static_configs:
    - targets: ["tomcat:8080"]
