{
 "title": "Example of Business Dashboard",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TIME_NOW",
    "query": "SELECT extract(epoch from now())"
   },
   {
    "name": "Region",
    "query": {
     "query": "label_values(reporting_patient_states_by_month,region)"
    }
   },
   {
    "name": "PATIENTS_UNDER_CARE",
    "query": {
     "query": "query_result(max(reporting_patient_states_by_month{region=\"${Region}\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All patients by Gender",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (date, gender)(reporting_patient_states_by_month{region=\"${Region}\"} @$TIME_NOW)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Patients by Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (date, outcome)(reporting_patient_states_by_month{region=\"${Region}\"} @$TIME_NOW ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypertension treatment outcomes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "Outcomes for ${PATIENTS_UNDER_CARE} patients under care in Region **${Region}**"
   }
  },
  {
   "title": "Control Rate",
   "type": "timeseries",
   "description": "BP controlled at latest visit in past 3 months",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "100* sum by (date)(reporting_patient_states_by_month{region=\"${Region}\", htn_care_state=\"under_care\",outcome=~\"controlled\"} @$TIME_NOW) / sum by (date)(reporting_patient_states_by_month{region=\"${Region}\", htn_care_state=\"under_care\",outcome=~\"controlled|uncontrolled|visited_no_bp|missed_visit\"} @$TIME_NOW)  ",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Not Controled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "100* sum by (date)(reporting_patient_states_by_month{region=\"${Region}\", htn_care_state=\"under_care\",outcome=~\"uncontrolled\"} @$TIME_NOW) / sum by (date)(reporting_patient_states_by_month{region=\"${Region}\", htn_care_state=\"under_care\",outcome=~\"controlled|uncontrolled|visited_no_bp|missed_visit\"} @$TIME_NOW)  ",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Missed Visit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "100* sum by (date)(reporting_patient_states_by_month{region=\"${Region}\", htn_care_state=\"under_care\",outcome=~\"missed_visit\"} @$TIME_NOW) / sum by (date)(reporting_patient_states_by_month{region=\"${Region}\", htn_care_state=\"under_care\",outcome=~\"controlled|uncontrolled|visited_no_bp|missed_visit\"} @$TIME_NOW)  ",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}