
name: Build Artefacts

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List things
        run: |
          ls -alrt $GITHUB_WORKSPACE
          find $GITHUB_WORKSPACE
          echo ${{ secrets.DOWNLOAD_ARTIFACT_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          repository: simpledotorg/rtsl_utils
          run-id: 240
          github-token: ${{ secrets.DOWNLOAD_ARTIFACT_TOKEN }}

      - name: List things
        run: |
          ls -alrt $GITHUB_WORKSPACE
          find $GITHUB_WORKSPACE
