
name: Build Artefacts

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          repository: simpledotorg/rtsl_utils
          run-id: 240
      - name: List things
        run: |
          wget -O $GITHUB_WORKSPACE/Dhis2Verifier.jar https://github.com/simpledotorg/rtsl_utils/actions/runs/11718214435/artifacts/2156228078
          ls -alrt $GITHUB_WORKSPACE
          find $GITHUB_WORKSPACE
