
name: Test Dockerd

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List things
        working-directory: ./docker_run
        run: |
          docker compose create
          dokcer compose run
