
name: Test Docker Compose Run

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List things
        run: |
          find .
          ls
      - name: start docker
        working-directory: ./docker_run
        run: |
          docker compose create
          docker compose up -d


          
