
name: Test Dockerd

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: List things
        run: |
          find .
          ls
      - name: start docker
        working-directory: ./docker_run
        run: |
          docker compose create
          dokcer compose run
