
name: Test Docker Compose Run

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - name: start docker
        working-directory: ./docker_run
        run: |
          docker compose create
          docker compose up -d
          sleep 10
          echo "waiting for docker system to start"
          docker compose stop prometheusdbexporter
          docker compose start
          echo "Docker system presumably started ..."
      - name: Check the image works fine
        run: |
          docker ps
          docker cp docker_run-prometheusdbexporter-1:/usr/local/tomcat/logs ./test_container_logs
          cat ./test_container_logs/*
          wget -O test.prom http://localhost:8080/PrometheusDbExporter/metrics
          cat test.prom
      - name: stop docker
        working-directory: ./docker_run
        run: |
          docker compose down

